name: Release [Build wheels]

on:
  pull_request:
    branches:
      - main

#on:
#  release:
#    types:
#      - created

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: # CIBW wheel tests need the right runner arch, so we use separate runners for macos
        os: [ ubuntu-latest, macos-latest, macos-12 ]

    steps:
      - uses: actions/checkout@v4

      - name: Install gfortran
        uses: fortran-lang/setup-fortran@v1
        if: ${{ matrix.os != 'ubuntu-latest' }}
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CC: ${{ matrix.os == 'ubuntu-latest' && 'gcc-13' || 'clang' }}  # believe it or not, this is a ternary operator
          FC: ${{ matrix.os == 'ubuntu-latest' && 'gcc-13' || 'gfortran' }}
          CIBW_BEFORE_ALL_LINUX: "yum install -y lapack-devel blas-devel"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: ${{ matrix.os == 'macos-latest' && 'arm64' || 'x86_64' }}
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_SKIP: "*-musllinux*"
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
          CIBW_BUILD_FRONTEND: "build"
          CIBW_TEST_REQUIRES: pytest~=6.2.2
          CIBW_TEST_COMMAND: pytest {project}/tests

        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Upload wheels to artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_wheels:
    name: upload wheels to cloudsmith
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v3
        with:
          path: wheelhouse

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Set up upload env
        run: |
          python -m pip install --upgrade pip
          python -m pip install cloudsmith-api cloudsmith-cli

      - name: Upload wheel to cloudsmith
        run: |
          for w in `find wheelhouse/ -type f -name "*.whl"` ; do cloudsmith push python quantinuum/internal "$w" -k ${{ secrets.CLOUDSMITH_TOKEN  }} ; done
